#include<stdio.h>
#include<math.h>

void main()
{
    int q;
    int a;

    printf("Enter the value of prime number:\n");
    scanf("%d",&q);

    printf("Enter the primitive root of prime number:\n");
    scanf("%d",&a);

    int X,Y;
    int N,M;

    printf("Enter the value of private key of A:\n");
    scanf("%d",&X);

    printf("Enter the value of private key of B:\n");
    scanf("%d",&Y);

    N=pow(a,X);
    int C=N%q;

    printf("The public key of A is :%d\n",C);

    M=pow(a,Y);
    int D=M%q;

    printf("The public key of B is :%d\n",D);

    int k1=pow(D,X);
    int v=k1%q;

    printf("the secret key generated by A is :%d\n",v);

    int k2=pow(C,Y);
    int w=k2%q;

    printf("the secret key generated by B is :%d\n",w);
}
